// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD72hF-TQN2bGOYw-xf9RPL_rXkzaW95cY',
    appId: '1:481512803877:web:b84cc0e9c939ef49b3b9cc',
    messagingSenderId: '481512803877',
    projectId: 'senior-fashion',
    authDomain: 'senior-fashion.firebaseapp.com',
    storageBucket: 'senior-fashion.firebasestorage.app',
    measurementId: 'G-0LT57CV5DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuoVmUObrEEplELNitKGUQ7GJPEuk6yzU',
    appId: '1:481512803877:android:aab30ebc529987f9b3b9cc',
    messagingSenderId: '481512803877',
    projectId: 'senior-fashion',
    storageBucket: 'senior-fashion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMM3wK38UrvW7Jo8QkwLX1tEq6tTrUJFI',
    appId: '1:481512803877:ios:8e94f6162ef64925b3b9cc',
    messagingSenderId: '481512803877',
    projectId: 'senior-fashion',
    storageBucket: 'senior-fashion.firebasestorage.app',
    iosBundleId: 'com.bmsahran.archiveapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMM3wK38UrvW7Jo8QkwLX1tEq6tTrUJFI',
    appId: '1:481512803877:ios:181a0e5e050dfd36b3b9cc',
    messagingSenderId: '481512803877',
    projectId: 'senior-fashion',
    storageBucket: 'senior-fashion.firebasestorage.app',
    iosBundleId: 'com.example.archiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD72hF-TQN2bGOYw-xf9RPL_rXkzaW95cY',
    appId: '1:481512803877:web:552ef19cfcccfb65b3b9cc',
    messagingSenderId: '481512803877',
    projectId: 'senior-fashion',
    authDomain: 'senior-fashion.firebaseapp.com',
    storageBucket: 'senior-fashion.firebasestorage.app',
    measurementId: 'G-7JVVR1RBKE',
  );
}
